[project]
name = "chatbot-created-by-claude-code"
version = "0.1.0"
description = "Streamlit-based AI chatbot using OpenAI API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.28.0",
    "openai>=1.0.0",
    "python-dotenv>=1.0.0"
]

# [project.scripts]
# chatbot = "streamlit run app.py"

[tool.hatch.build.targets.wheel]
packages = ["."]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
